th train.lua \
    -data /media/bigdrive/dingyang/dataset \
    -style_image ~/pt_test/hd2.png \
    -style_size 600 \
    -image_size 512 \
    -model johnson \
    -batch_size 2 \
    -learning_rate 0.005 \
    -style_weight 30 \
    -style_layers relu1_2,relu2_2,relu3_2,relu4_2 \
    -content_layers relu4_2 \
    -checkpoints_path data/checkpoints/ \
    -gpu 1 \
    > train_hd2.log 2>&1
